### ISSUE TITLE
Server failes to create “bso” table on MySQL 5.6.25

### ISSUE THREAD

**Issue by max-m** [mozilla-services/server-syncstorage#23] opened 2015-06-29 18:15 UTC
The server is unable to create the “bso” table when using a MySQL (5.6.25) database and stops with error code 3.

```
root@0ee9c641a76d:/home/ffsync/syncserver# make serve
./local/bin/gunicorn --paste ./syncserver.ini
Makefile:46: recipe for target 'serve' failed
make: *** [serve] Error 3
root@0ee9c641a76d:/home/ffsync/syncserver#
```

Note: This is a Docker container

After creating the table by hand the server starts without a problem.

The SQL query I used:

``` sql
DROP TABLE IF EXISTS `bso`;
CREATE TABLE `bso` (
  `userid` int(11) NOT NULL,
  `collection` int(11) NOT NULL,
  `id` varchar(60) NOT NULL,
  `sortindex` int(11) NOT NULL DEFAULT '0',
  `modified` bigint(20) NOT NULL,
  `payload` mediumtext NOT NULL,
  `payload_size` int(11) NOT NULL DEFAULT '0',
  `ttl` int(11) NOT NULL DEFAULT '2100000000',
  PRIMARY KEY (`userid`,`collection`,`id`),
  KEY `bso_ttl_idx` (`ttl`),
  KEY `bso_usr_col_mod_idx` (`userid`,`collection`,`modified`),
  KEY `sortindex` (`sortindex`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Edit: Removed auto increment from `sortindex`.

**Comment by rfk** [comment] 2015-07-03 00:23
> Note: This is a Docker container

Anything particularly interesting about this docker container that might be triggering the issue?

**Comment by rfk** [comment] 2016-04-17 21:48
This may be caused by the schema issue that @rtilder identified in https://github.com/mozilla-services/server-syncstorage/pull/32

**Comment by rfk** [comment] 2016-04-17 22:02
More specifically, from the diff:
```
 +        # MySQL no likey "DEFAULT ''".  Results in an error:
+        #     ERROR 1101 (42000): BLOB, TEXT, GEOMETRY or JSON column 'payload'
+        #                         can't have a default value
+        #
+        # By adding the following lines to my.cnf you can turn the fatal error
+        # into a warning:
+        #
+        # [mysqld]
+        # sql_mode=MYSQL40
+        #
         Column("payload", PAYLOAD_TYPE, nullable=False, server_default=""),
```

We can probably remove the `server_default` declaration here with no ill effect.

**Comment by rfk** [comment] 2018-05-25 01:17
IIUC this should be fixed as of https://github.com/mozilla-services/server-syncstorage/commit/ec7df92d6ae456046d1114107b18113e4bcaafac

**Closed by rfk** 2018-05-25 01:17 UTC
